apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps 
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-cd/
    repoURL: 'git@github.com:ralphtatt/argo-test.git'
    targetRevision: HEAD
    helm:
      valuesObject:
        environment: dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
