apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/local-app
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - app-1.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
