apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-local-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/local-app
    repoURL: 'https://github.com/ralphtatt/argo-test.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
